<a href="https://colab.research.google.com/github/tnaka78/numpy_study/blob/master/numpy_array_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy学習（ソートAPI）

In [0]:
import numpy as np

## np.sort
配列のソート

In [2]:
a = np.array([1, 4, 3, 5, 2])
sorted = np.sort(a)
print(sorted)
print(sorted[::-1]) # 降順のソート（昇順にソートした後、その配列を逆転させる）

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
a = np.array([[1, 4, 3, 5, 2], [5, 4, 3, 2, 1]])
sorted = np.sort(a)
print(sorted)
print(sorted[:, ::-1]) # 降順のソート（昇順にソートした後、その配列を逆転させる）

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[5 4 3 2 1]
 [5 4 3 2 1]]


## np.argsort
ソートした配列のインデックスを返す。
（この順番に元の配列にアクセスすると、ソートされた配列が得られる）

In [4]:
a = np.array([[1, 4, 3, 5, 2], [5, 4, 3, 2, 1]])
indices = np.argsort(a)
print(indices)

[[0 4 2 1 3]
 [4 3 2 1 0]]


In [5]:
# 元の配列の符号を変えてからソートすると降順になる。
a = np.array([[1, 4, 3, 5, 2], [5, 4, 3, 2, 1]])
indices = np.argsort(-a)
print(indices)

[[3 1 2 4 0]
 [0 1 2 3 4]]
