<a href="https://colab.research.google.com/github/tnaka78/numpy_study/blob/master/numpy_array_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy学習（配列操作系API）

In [0]:
import numpy as np

## np.reshape
配列を変形する。

In [2]:
# [1, 12] -> [3, 4]
a = np.arange(0, 12)
mat = np.reshape(a, (3, 4))
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
# [3, 4] -> [2, 6]
mat1 = np.reshape(np.arange(0, 12), (3, 4))
mat2 = np.reshape(mat1, (2, 6))
print(mat2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## np.tile
配列を繰り返して拡張する。

In [4]:
mat = np.tile(0.5, [4, 3])
print(mat)

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [5]:
a = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33 ,34]])
mat = np.tile(a, [2, 3])
print(mat)

[[11 12 13 14 11 12 13 14 11 12 13 14]
 [21 22 23 24 21 22 23 24 21 22 23 24]
 [31 32 33 34 31 32 33 34 31 32 33 34]
 [11 12 13 14 11 12 13 14 11 12 13 14]
 [21 22 23 24 21 22 23 24 21 22 23 24]
 [31 32 33 34 31 32 33 34 31 32 33 34]]


## np.column_stack


In [6]:
a1 = np.array([11, 12, 13])
a2 = np.array([21, 22, 23])
mat = np.column_stack((a1, a2))
print(mat)

[[11 21]
 [12 22]
 [13 23]]


## np.row_stack

In [7]:
a1=np.array([11, 12, 13])
a2=np.array([21, 22, 23])
mat = np.row_stack((a1, a2))
print(mat)

[[11 12 13]
 [21 22 23]]
